[build]
  command = "npm run build"
  publish = "client/dist"

# Functions directory
[functions]
  directory = "netlify/functions"

# Development server settings
[dev]
  command = "npm run dev" # This now runs `vite`
  targetPort = 5173      # Default Vite port
  port = 8888            # Port for Netlify Dev to listen on

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
